DATA:
  DATA_NAME: 'ENIGMA'
  CLIP_MIXUP_RATE: 0.5
  CLIP_MIXUP_SAMPLE: 'uniform'
INPUT:
  MODALITY: 'visual'
  VISUAL_FEATURE: 'EfficientNetV2_distilled'
  MOTION_FEATURE: 'EfficientNetV2_distilled' # not used
  OBJECT_FEATURE: 'EfficientNetV2_distilled' # not used
  TARGET_PERFRAME: 'target_end_perframe_cdc'
OUTPUT:
  MODALITY: 'action' 
MODEL:
  MODEL_NAME: 'LSTR'
  FEATURE_HEAD:
    LINEAR_ENABLED: True
    LINEAR_OUT_FEATURES: 2048
  LSTR:
    MAMBA_LAYER: 0
    NUM_HEADS: 8
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.1
    DROPOUT_CLS: 0.5
    ACTIVATION: 'relu'
    LONG_MEMORY_SECONDS: 0
    LONG_MEMORY_SAMPLE_RATE: 1
    LONG_MEMORY_INCLUDE_WORK: False
    WORK_MEMORY_SECONDS: 1
    WORK_MEMORY_SAMPLE_RATE: 1
    ENC_MODULE: [
      [16, 1, True], [16, 2, True]
    ]
    DEC_MODULE: [-1, 2, True]
    LOSS_WEIGHT_V: 1.
    LOSS_WEIGHT_N: 1.
    FUSION_WEIGHT_V: 1.
    FUSION_WEIGHT_N: 1.
  CRITERIONS: [['FOCAL', {}]]
  FRAME_DELTA: 0
DATA_LOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 8
  PIN_MEMORY: True
SOLVER:
  NUM_EPOCHS: 100
  OPTIMIZER: 'adamw'
  BASE_LR: 5e-05
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    SCHEDULER_NAME: 'warmup_cosine'
    WARMUP_FACTOR: 0.3
    WARMUP_EPOCHS: 5.0
    WARMUP_METHOD: 'linear'
OUTPUT_DIR: 'ckpt'
